print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Selectn:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Selectn:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Selectn:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Select operation:")
print("Selectn:")
print("Select operation:")